[package]
name = "qfbvsmtrs"
version.workspace = true
edition.workspace = true
description = "Standalone pure-Rust QF_BV SMT solver via bit-blasting"
license.workspace = true

[features]
default = []
wire = ["dep:smt-wire"]

[dependencies]
smt-qfbv-smtlib.workspace = true
smt-wire = { workspace = true, optional = true }
varisat.workspace = true
splr.workspace = true

[dev-dependencies]
z3.workspace = true
