[package]
name = "smt-server"
version.workspace = true
edition.workspace = true
description = "Reference SMT wire-format server and backends"
license.workspace = true

[dependencies]
binbit.workspace = true
qfbvsmtrs = { workspace = true, features = ["wire"] }
rumba-core.workspace = true
smt-qfbv-smtlib.workspace = true
smt-wire.workspace = true
blake3.workspace = true
rusqlite.workspace = true
z3.workspace = true

[dev-dependencies]
rumba-core = { workspace = true, features = ["parse"] }
